config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :tweets
    resources :replies, controller: 'tweets', type: 'Reply'
  end

  resources :tweets do
    resources :replies, controller: 'tweets', type: 'Reply'
  end

  resources :sessions
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/reply.rb
class Reply < Tweet

  belongs_to :tweet
  belongs_to :user
end

app/models/retweet.rb
class Retweet < Tweet

  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  belongs_to :user
  has_many :replies, class_name: 'Tweet'
  validates :text, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tweets, dependent: :destroy
  has_many :replies, class_name: 'Reply'
  has_secure_password

  PASSWORD_FORMAT = /\A(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[[:^alnum:]])/x

  validates :first_name, :last_name, presence:true
  validates :email, format: {with: /.+@.+\..+/i, message: 'only valid emails allowed'}, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, format: { with: PASSWORD_FORMAT}, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    if current_user.nil?
      redirect_to(
        root_path, alert: 'You must be logged in to access this page'
      )
    end
  end

  def authorized
    if current_user
      redirect_to(
        user_path(current_user)
      )
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :authorized

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authorize

  def show
    @tweets = Tweet.order(created_at: :desc)
    render partial: 'tweets/tweet', collection: @tweets
  end

  def show_replies
    @tweets = Tweet.order(created_at: :desc)
    render partial: 'tweets/reply', collection: @tweets
  end

  def new
    @tweets = Tweet.order(created_at: :desc)
    @tweet = Tweet.find(params[:tweet_id])
    @reply = @tweet.replies.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.tweet_id.present?
      @tweet.type = 'Reply'
    end
    respond_to do |format|
      if @tweet.save
        if @tweet.type == 'Reply'
          format.html { redirect_to new_tweet_reply_path(@tweet.tweet_id) }
          format.json { render json: @reply, status: :created, location: @tweet }
        else
          format.html { redirect_to user_path(current_user) }
          format.json { render json: @tweet, status: :created, location: @tweet }
        end
      else
        flash[:notice] = 'Tweet has errors!'
        if @tweet.type == 'Reply'
          redirect_to new_tweet_reply_path(@tweet.tweet_id)
        else
          redirect_to user_path(current_user)
        end
      end
    end
  end

  def edit
    @tweets = Tweet.order(created_at: :desc)
    @tweet = Tweet.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
     if @tweet.type == 'Reply'
        redirect_to new_tweet_reply_path(@tweet.tweet_id)
      else
        redirect_to user_path(current_user)
      end
    else
      flash[:notice] = 'Tweet has errors!'
      if @tweet.type == 'Reply'
        redirect_to new_tweet_reply_path(@tweet.tweet_id)
      else
        redirect_to user_path(current_user)
      end
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.find_by_id(params[:id])
    if @tweet.present? && @tweet.destroy
      if @tweet.type == 'Reply'
        redirect_to new_tweet_reply_path(@tweet.tweet_id)
      else
        redirect_to user_path(current_user)
      end
    else
      flash[:notice] = 'Tweet has already been deleted!'
      redirect_to user_path(current_user)
    end
  end


  protected

  def set_type
    case params[:type]
    when 'Reply'
      'reply'
    else
      'tweet'
    end
  end


  private

  def tweet_params
    params.require(set_type.to_sym).permit(:type, :text, :tweet_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:new, :create]
  before_action :authorized, except: [:show]

  def new
    @user = User.new
  end

  def show
    @tweets = Tweet.order(created_at: :desc)
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end


private

  def user_params
    params.require(:user).
      permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class='navbar navbar-default'>
  <div class='container-fluid'>
    <% if current_user %>
      <div>
        <%= link_to image_tag('PseudoTwitterIcon.png', size: '60x40'), user_path(current_user), class: 'navbar-brand', style: 'top: -10px' %>
        <span class='navbar-brand' style='left: 60px'>
          Logged in as <%= current_user.email %>
        </span>
      </div>
      <ul class='nav navbar-nav navbar-right'>
        <li class='nav-item'>
          <%= link_to 'Home', user_path(current_user) %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Log Out', session_path(current_user), method: :delete %>
        </li>
      </ul>
    <% else %>
      <div class='navbar-header'>
        <%= link_to image_tag('PseudoTwitterIcon.png', size: '60x40'), root_path, class: 'navbar-brand', style: 'top: -10px' %>
        <a class='navbar-brand' style='left: 60px'>Pseudotwitter</a>
      </div>
      <ul  class='nav navbar-nav navbar-right'>
        <li class='nav-item'>
          <%= link_to 'Log In', new_session_path %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Sign Up', new_user_path %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pseudotwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation' %>

  <div class='container'>
    <body>
      <% if notice %>
        <%= notice %>
      <% end %>
      <% if alert %>
        <%= alert %>
      <% end %>
      <%= yield %>
    </body>
  </div>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tweets/_edit.html.erb
<h2>Tweet</h2>
<%= render 'tweets/form2' %>
<%= render 'users/tweets' %>

app/views/tweets/_form.html.erb
<%= form_for @user.tweets.build, remote: true do |form| %>
  <div>
    <%= form.text_area :text, class: 'form-control', id: 'text', maxlength: 140, required: true %>
    Character limit: <span id='counter'>0</span>/140
    <%= form.submit 'Tweet', class: 'btn btn-primary btn-lg', id: 'tweet_submit' %>
  </div>
<% end %>

<script>
  var this_text = document.getElementById('text');
  var counter = document.getElementById('counter');

  this_text.addEventListener('keyup', function() {
    var characters = this_text.value.split('');
    counter.innerText = characters.length;
  });
</script>

app/views/tweets/_form2.html.erb
<%= form_for @tweet do |form| %>
  <div>
    <%= form.text_area :text, class: 'form-control', id: 'text', maxlength: 140, required: true %>
    Character limit: <span id='counter'>0</span>/140
    <%= form.submit 'Update Tweet', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

<script>
  var this_text = document.getElementById('text');
  var counter = document.getElementById('counter');

  this_text.addEventListener('keyup', function() {
    var characters = this_text.value.split('');
    counter.innerText = characters.length;
  });
</script>

app/views/tweets/_form3.html.erb
<%= form_for @reply, remote: true do |form| %>
  <div>
    <%= form.text_area :text, class: 'form-control', id: 'text', maxlength: 140, required: true %>
    Character limit: <span id='counter'>0</span>/140
    <%= form.hidden_field :tweet_id %>
    <%= form.submit 'Reply', class: 'btn btn-primary btn-lg', id: 'reply_submit' %>
  </div>
<% end %>

<script>
  var this_text = document.getElementById('text');
  var counter = document.getElementById('counter');

  this_text.addEventListener('keyup', function() {
    var characters = this_text.value.split('');
    counter.innerText = characters.length;
  });
</script>

app/views/tweets/_form4.html.erb
<%= form_for @tweet, url: user_reply_path(@tweet) do |form| %>
  <div>
    <%= form.text_area :text, class: 'form-control', id: 'text', maxlength: 140, required: true %>
    Character limit: <span id='counter'>0</span>/140
    <%= form.submit 'Update Reply', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

<script>
  var this_text = document.getElementById('text');
  var counter = document.getElementById('counter');

  this_text.addEventListener('keyup', function() {
    var characters = this_text.value.split('');
    counter.innerText = characters.length;
  });
</script>

app/views/tweets/_new.html.erb
<% if params[:type] != 'Reply' %>
  <%= render 'tweets/form' %>
<% else %>
  <%= render 'tweets/form3' %>
<% end %>

app/views/tweets/_replies.html.erb
<table class='table' style='width: 100%'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>User</th>
      <th scope='col'>Text</th>
      <th scope='col'>Created</th>
    </tr>
  </thead>
  <tbody id="replies">
    <%= render partial: 'tweets/reply', collection: @tweets, as: :tweet %>
  </tbody>
</table>

app/views/tweets/_reply.html.erb
<% if tweet.tweet_id == @tweet.id %>
  <tr>
    <td><%= tweet.user.first_name + ' ' + tweet.user.last_name %></td>
    <td style='word-wrap: break-word;min-width: 160px;max-width: 160px;'><%= tweet.text %></td>
    <td>created <%= time_ago_in_words tweet.created_at %> ago</td>
    <td><%= link_to 'Reply', new_tweet_reply_path(tweet) %>
    <% if tweet.user_id == current_user.id %>
      <td><%= link_to 'Edit', edit_user_tweet_path(current_user, tweet) %></td>
      <td><%= link_to 'Delete', [tweet.user, tweet], method: :delete, data: {confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

app/views/tweets/_show.html.erb
<h1><%= @tweet.user.first_name + ' ' + @tweet.user.last_name %></h1>
<h2><%= @tweet.text %></h2>
<% render 'tweets/new' %>
<%= link_to 'Back', user_path(@tweet.user) %>

app/views/tweets/_tweet.html.erb
<% if tweet.tweet_id == nil %>
  <tr>
    <td><%= tweet.user.first_name + ' ' + tweet.user.last_name %></td>
    <td style='word-wrap: break-word;min-width: 160px;max-width: 160px;'><%= tweet.text %></td>
    <td>created <%= time_ago_in_words tweet.created_at %> ago</td>
    <td><%= link_to 'Reply', new_tweet_reply_path(tweet) %></td>
    <% if tweet.user_id == current_user.id %>
      <td><%= link_to 'Edit', edit_user_tweet_path(current_user, tweet) %></td>
      <td><%= link_to 'Delete', [tweet.user, tweet], method: :delete, data: {confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

app/views/tweets/_tweets.html.erb
<h3>Published Tweets</h3>
<table class='table' style='width: 100%'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>User</th>
      <th scope='col'>Text</th>
      <th scope='col'>Created</th>
    </tr>
  </thead>
  <tbody id='tweets' >
    <%= render partial: 'tweets/tweet', collection: @tweets %>
  </tbody>
</table>

app/views/tweets/edit.html.erb
<% if @tweet.type == 'Reply' %>
  <% orig_tweet = Tweet.find(@tweet.tweet_id) %>
  <h1>Tweeter: <%= orig_tweet.user.first_name + ' ' + orig_tweet.user.last_name %></h1>
  <h2 style='word-wrap: break-word'>Message: <%= orig_tweet.text %></h2>
  <%= render 'tweets/form4' %>
  <%= link_to 'Back', user_path(current_user), class: 'btn btn-danger btn-lg btn-block' %>
  <% @tweet = orig_tweet %>
  <%= render 'tweets/replies' %>
<% else %>
  <div class='row'>
    <aside class='col-md-4'>
      <section class='user_info'>
        <h1><%= current_user.last_name %></h1>
        <h3><%= current_user.first_name %></h3>
        <h5><%= current_user.email %></h5>
      </section>
    </aside>
    <div class='col-md-8'>
      <%= render 'tweets/form2' %>
      <%= render 'tweets/tweets' %>
    </div>
  </div>
<% end %>

app/views/tweets/new.html.erb
<h1>Tweeter: <%= @tweet.user.first_name + ' ' + @tweet.user.last_name %></h1>
<h2 style='word-wrap: break-word'>Message: <%= @tweet.text %></h2>
<%= render 'tweets/new' %>
<%= link_to 'Back', user_path(@tweet.user), class: 'btn btn-danger btn-lg btn-block' %>
<%= render 'tweets/replies' %>

app/views/tweets/show.html.erb
<h1><%= @tweet.user.first_name + ' ' + @tweet.user.last_name %></h1>
<h2><%= @tweet.text %></h2>
<%= render 'tweets/form3' %>
<%= link_to 'Back', user_path(@user) %>

app/views/users/new.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for @user do |form| %>
    <h1 class='mb-3 font-weight-normal'>Sign Up</h1>
    <div style='font-size: 9.5px; color: blue'>
          *Please fill up all fields
    </div>
    <%= render 'shared/error_messages' %>
      <div class='form-group' style='text-align: left'>
        <%= form.label :first_name %><br>
        <%= form.text_field :first_name, class: 'form-control', required: true %>
      </div>
      <div class='form-group' style='text-align: left'>
        <%= form.label :last_name %><br>
        <%= form.text_field :last_name, class: 'form-control', required: true %>
      </div>
      <div class='form-group' style='text-align: left'>
        <%= form.label :email %><br>
        <%= form.email_field :email, class: 'form-control', required: true %>
      </div>
      <div class='form-group' style='text-align: left'>
        <%= form.label :password %><br>
        <%= form.password_field :password, class: 'form-control', required: true %>
        <div style='font-size: 9.5px'>
          *Must contain more than 8 characters with 1 capital letter, 1 small letter, 1 digit, and 1 special character
        </div>
      </div>
      <div class='form-group' style='text-align: left'>
        <%= form.label :password_confirmation %><br>
        <%= form.password_field :password_confirmation, class: 'form-control', required: true %>
      </div>
      <%= form.submit 'Create Account', class: 'btn btn-primary btn-lg' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class='row'>
  <aside class='col-md-4'>
    <section class='user_info'>
      <h1><%= current_user.first_name %></h1>
      <h5><%= current_user.email %></h5>
    </section>
  </aside>
  <div class='col-md-8'>
    <%= render 'tweets/new' %>
    <%= render 'tweets/tweets' %>
  </div>
</div>